// 11935 TERMINAL MA PIEDRAS NEGRAS
// 13650 TERMINAL MA QUERETARO
// 14064 TERMINAL MA GUADALAJARA
// 14082 COMBUSTIBLE TRANSITORIO
// 14235 TERMINAL MA AGUASCALIENTES
// 14477 TERMINAL MA TEOLOYUCAN

export const TERMINAL_MA_PIEDRAS_NEGRAS = {
  id: 11935,
  name: 'TERMINAL MA PIEDRAS NEGRAS'
}

export const TERMINAL_MA_QUERETARO = {
  id: 13650,
  name: 'TERMINAL MA QUERETARO'
}

export const TERMINAL_MA_GUADALAJARA = {
  id: 14064,
  name: 'TERMINAL MA GUADALAJARA'
}

export const COMBUSTIBLE_TRANSITORIO = {
  id: 14082,
  name: 'COMBUSTIBLE TRANSITORIO'
}

export const TERMINAL_MA_AGUASCALIENTES = {
  id: 14235,
  name: 'TERMINAL MA AGUASCALIENTES'
}

export const TERMINAL_MA_TEOLOYUCAN = {
  id: 14477,
  name: 'TERMINAL MA TEOLOYUCAN'
}

export const TERMINALS = [
  TERMINAL_MA_PIEDRAS_NEGRAS,
  TERMINAL_MA_QUERETARO,
  TERMINAL_MA_GUADALAJARA,
  COMBUSTIBLE_TRANSITORIO,
  TERMINAL_MA_AGUASCALIENTES,
  TERMINAL_MA_TEOLOYUCAN
]
